### ISSUE TITLE
How to fix this.

### ISSUE THREAD

**Issue by chardy13** [MrFums/Valbot#14]
It happens when I choose 1. 
https://imgur.com/a/87M1P81

**Comment by MrFums** [comment]
Did you follow the instructions?

**Comment by chardy13** [comment]
> Did you follow the instructions?

yes. I'm using python 3.8.0.

**Comment by MrFums** [comment]
Did you run the installer bat file?

**Comment by chardy13** [comment]
> Did you run the installer bat file as admin?

yes.

**Comment by MrFums** [comment]
> > Did you run the installer bat file as admin?
> 
> yes.

It seems to be a problem with python then. Uninstall all packages with pip and / or uninstall python with iobit uninstaller and then reinstall

**Comment by chardy13** [comment]
I already did both, but it's still the same. I added you on discord.

**Comment by MrFums** [comment]
Assuming this is fixed
