### ISSUE TITLE
Bot not clicking 'play again' button in v1.7

### ISSUE THREAD

**Issue by tkien212** [MrFums/Valbot#20]
I have 1920x1080 full screen settings on, and the bot can detect the 'play again' button but not clicking it

[-] SEARCHING FOR PLAY AGAIN BUTTON

[√] DETECTED PLAY AGAIN BUTTON

[-] DETECTING IF IN QUEUE

[!] DETECTED NOT IN QUEUE

[-] SEARCHING FOR A SKIP BUTTON

[√] COULD NOT DETECT A SKIP BUTTON

[-] SEARCHING FOR PLAY AGAIN BUTTON

[√] DETECTED PLAY AGAIN BUTTON

[-] DETECTING IF IN QUEUE

[!] DETECTED NOT IN QUEUE

[-] SEARCHING FOR A SKIP BUTTON

[√] COULD NOT DETECT A SKIP BUTTON

[-] SEARCHING FOR PLAY AGAIN BUTTON

[√] DETECTED PLAY AGAIN BUTTON

**Comment by tkien212** [comment]
I have 1920x1080 full screen settings on, and the bot can detect the 'play again' button but not clicking it

[code] [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON

 [√] DETECTED PLAY AGAIN BUTTON

 [-] DETECTING IF IN QUEUE

 [!] DETECTED NOT IN QUEUE

 [-] SEARCHING FOR A SKIP BUTTON

 [√] COULD NOT DETECT A SKIP BUTTON

 [-] SEARCHING FOR PLAY AGAIN BUTTON[/code]

**Comment by MrFums** [comment]
So does it crash or does it just not click it? It should check if you are in the queue after it has clicked it. If you're not in the queue, it tries to run the function again.

**Comment by tkien212** [comment]
Just not clicking it. I edited the coordinates for playagain and playagain2 and its working now. The coordinates you had is like in the middle of the screen for me.

**Comment by MrFums** [comment]
It is supposed to click the button > click middle of screen > click the button
