### ISSUE TITLE
stuck on searching for play button

### ISSUE THREAD

**Issue by C0ldezra** [MrFums/Valbot#22]
I load in bot.py and it says it will load in 15 seconds I go into valorant select it then press home, I wait 15 seconds nothing happends I go back to see on bot.py it says searching for play button.

**Comment by C0ldezra** [comment]
Sorry I just realised it might be to resolution then I change to 1920 and it works perfectly.

**Comment by MrFums** [comment]
Glad you solved it yourself, yes the bot only works in 1920 x 1080 unless you change the images in `images/` folder explicitly

**Comment by horaira69** [comment]
I have the same problem and it's not fixed for me
