### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by FabricioSchimidt** [MrFums/Valbot#24]
I start waiting for the 10 seconds but this error:
![Captura de Tela (2)](https://user-images.githubusercontent.com/74165104/98498150-d1dcaf00-2224-11eb-8394-70b5f798fc1c.png)

**Comment by MrFums** [comment]
Try download the latest version from releases.

**Comment by MrFums** [comment]
Here is the fix: If you have the crash when you load into the bot script / when you press 1 to begin the bot, you need to uninstall numpy ( `pip uninstall numpy` ) and install an older version of numpy: `pip install numpy==1.19.3`

Then download the latest version from releases.
