### ISSUE TITLE
Bot unable to reopen after 2 hours

### ISSUE THREAD

**Issue by tkien212** [MrFums/Valbot#25]
Using v1.7.4
I'm not sure how to get an error code. After 2 hours, the bot closed on its own and doesn't reopen.
The file 'restart.py' works fine

**Comment by MrFums** [comment]
Potentially fixed in v1.7.5
Please try it and let me know if it works. Thanks for telling me that `restart.py` works normally, I think I have diagnosed and fixed the problem.

Download [here](https://github.com/MrFums/Valbot/releases/latest)

**Comment by tkien212** [comment]
confirmed it is fixed. 
Just a small visual issue, discord and startup message now shows outdated

**Comment by MrFums** [comment]
> Just a small visual issue, discord and startup message now shows outdated

fixed in latest release.
