### ISSUE TITLE
The cursor isn't moving. 

### ISSUE THREAD

**Issue by Thrownawaygarbage** [MrFums/Valbot#28]
Hey, I'm on the latest branch (1.7.6) using python 3.80, and when I use the bot, it's able to detect the play button and start button; however, it doesn't the cursor doesn't move on its own. I've followed all of the instructions given, but it doesn't want to work. 

![val123](https://user-images.githubusercontent.com/74338082/98891937-1732f380-2454-11eb-908a-4d05fad78646.png)

**Comment by Thrownawaygarbage** [comment]
I've done this already "If you have the crash when you load into the bot script / when you press 1 to begin the bot, you need to uninstall numpy ( pip uninstall numpy ) and install an older version of numpy: pip install numpy==1.19.3" and I've made sure that my resolution was at 1920x1080.

**Comment by WolfAnto** [comment]
Add me on discord, I will try to help you ( WolfAnto#5183 )

**Comment by MrFums** [comment]
assuming fixed
