### ISSUE TITLE
DON'T KNOW HOW TO ADD VALORANT IN DIRECTORY

### ISSUE THREAD

**Issue by Wenseph** [MrFums/Valbot#29]
Please help how to add valorant in directory
![98633546-9e9d3b80-235c-11eb-873b-076af04323dc](https://user-images.githubusercontent.com/74340774/98897576-b274a900-24e6-11eb-9d2a-5c78bafeb68f.png)

**Comment by WolfAnto** [comment]
Press Windows key > type Valorant > right click on valorant > open directory folder > copy VALORANT > paste in Valbot folder

**Comment by Wenseph** [comment]
Done adding but the BOT is not working.
