### ISSUE TITLE
Lower Resolutions

### ISSUE THREAD

**Issue by EngineLess** [MrFums/Valbot#33]
Make some lower reolutions like 1900x600

**Comment by MrFums** [comment]
The user can do this themselves. As over 60% of players, going by steams data, play on 1920x1080 I will not be adding different resolutions as it would create way too much work for it to be worthwhile. (See data here) 
![image](https://user-images.githubusercontent.com/57535680/101982664-88d9a980-3c6d-11eb-8952-a422bf4558f9.png)

If you are wondering how to make your own resolution, head to the `images` folder and make your own version of the images from your own game.
