### ISSUE TITLE
Valorant Shortcut exp bot

### ISSUE THREAD

**Issue by predvvx** [MrFums/Valbot#36]
I added Valorant shortcut and when im opening bot it doesn't work and all time information about no shortcut in folder

**Comment by MrFums** [comment]
Is the shortcut named VALORANT? has to be exact, like this;
![image](https://user-images.githubusercontent.com/57535680/101982580-f3d6b080-3c6c-11eb-94bc-d7b63e524152.png)

**Comment by MrFums** [comment]
assuming fixed
