### ISSUE TITLE
stuck on Searching for Play Button!

### ISSUE THREAD

**Issue by horaira69** [MrFums/Valbot#37]
I have followed the steps correctly but still, the bot gets stuck on " Searching for play button " it's super annoying. If you know any fix it would really help me out

**Comment by horaira69** [comment]
I fixed the issue mentioned above by taking my own pictures in the /images folder and changing the screen to "fullscreen borderless" but now there is another problem. The first game starts with no issues but when the play again option comes up it doesn't work the bot says "Detecting skip button" then "Couldn't find skip button" then the bot tries to fing the play again button but cant.

**Comment by horaira69** [comment]
I have fixed the "searching for play button" issue as well by editing the "bot" with notepadd++ and setting it to: 
![image](https://user-images.githubusercontent.com/75175751/101118001-4a067c80-35f9-11eb-8b88-9a5bcb5a9968.png)

**Comment by MrFums** [comment]
Thank you to @iNfeKTzia for fixing this issue. Pushed to [v1.7.7](https://github.com/MrFums/Valbot/releases/tag/1.7.7), please update your program.
