### ISSUE TITLE
Not clicking the play button

### ISSUE THREAD

**Issue by SolarStorm0521** [MrFums/Valbot#38]
Everything is installed and running and in full screen. It says it has found the play button but that is it. It does nothing else after that.

**Comment by SolarStorm0521** [comment]
It will click the play button now but will not start a game. Just keeps saying it sees the play button but tries to click it instead of deathmatch or start.

**Comment by Rabbicabeans** [comment]
Same issue.

**Comment by iNfeKTzia** [comment]
Hey, I fixed the bug. you can take it from my fork.

**Comment by MrFums** [comment]
Thank you to @iNfeKTzia for fixing this issue. Pushed to [v1.7.7](https://github.com/MrFums/Valbot/releases/tag/1.7.7), please update your program.
