### ISSUE TITLE
Stuck on Searching for play button

### ISSUE THREAD

**Issue by vladz4you** [MrFums/Valbot#40]
I tried everything, but after opening the game it doesnt do anything, it just says thats its looking for the play button. My resolution is 1920x1080. I tried to do fullscreen/borderless and it doesnt work.

**Comment by vladz4you** [comment]
It detects the play button, but says its not selected

**Comment by iNfeKTzia** [comment]
Do you use ver. 1.7.7?

**Comment by vladz4you** [comment]
Yes, i even tried the older version but it didnt even let me start before updating.

**Comment by iNfeKTzia** [comment]
Your game UI on English?

**Comment by vladz4you** [comment]
Yes.

**Comment by turboturtl** [comment]
I was having the same problem, but after some troubleshooting i got it to work. my solution was to disconnect my other monitor.
after this it worked absolutely fine

**Comment by bakoki098** [comment]
me too stuck on searching play button but if i close and exit the valorant game suddenly the code said that play button found help thanks

**Comment by MrFums** [comment]
Sorry for the time it took to fix this, it was an annoying one but I managed to fix it finally. It is available [here, in 1.7.8](https://github.com/MrFums/Valbot/releases/tag/1.7.8)
