### ISSUE TITLE
Need help with valorant bot crashing (reinstalled pip numpy already)

### ISSUE THREAD

**Issue by redefice** [MrFums/Valbot#41]
What the title says I tried reinstalling it to 1.19.3 and that didnt work so then i tried 1.19.4 (newest version at time) help please?

**Comment by MrFums** [comment]
Did you read everything in read me?

**Comment by redefice** [comment]
Yeah i read everything and followed the instructions, if it helps the bot loads into the code and shows the screen for like a split second then dissapears

**Comment by MrFums** [comment]
Sounds like this issue to me: In addition to this, if your program crashes and / or you have an error message that contains psutil.AccessDenied, you must download a different python version.

Link: [README](https://github.com/MrFums/Valbot#help)

**Comment by MrFums** [comment]
assuming fixed
