### ISSUE TITLE
It doesnt start the next match

### ISSUE THREAD

**Issue by some1crzy** [MrFums/Valbot#42]
I start bot it runs game and detects everything but after match it doesnt click on play again (bot detects the play again button but it doesnt click on it)

**Comment by karthikone** [comment]
I have this problem too

**Comment by shookdiamond** [comment]
I have this problem too

**Comment by MrFums** [comment]
Sorry for the time it took to fix this, it was an annoying one but I managed to fix it finally. It is available [here, in 1.7.8](https://github.com/MrFums/Valbot/releases/tag/1.7.8)
