### ISSUE TITLE
Need help with valorant bot (after game)

### ISSUE THREAD

**Issue by redefice** [MrFums/Valbot#43]
I installed the newest version 1.7.7, have my resolution at 1920x1080 and it will find and enter a game perfectly by itself but when the game ends and its time to find a new one all it does is search for buttons, it goes
- Searching for a skip button
V could not detect a skip button
- Searching for  play again button
V detected play again button
- Detecting if in queue
! Detected not in queue
Then it goes in a loop from there

**Comment by shookdiamond** [comment]
I have this problem too

**Comment by MrFums** [comment]
Sorry for the time it took to fix this, it was an annoying one but I managed to fix it finally. It is available [here, in 1.7.8](https://github.com/MrFums/Valbot/releases/tag/1.7.8)
