### ISSUE TITLE
searching play button 

### ISSUE THREAD

**Issue by ardahan1423** [MrFums/Valbot#52]
-searching play button it writes like this and doesn't play by itself

**Comment by MrFums** [comment]
What resolution?

**Comment by metzenbaum98** [comment]
i have 1920x1080 res and have the same problem too with the v1.7.8, do you have the solution?

**Comment by metzenbaum98** [comment]
UPDATE: i tried using windowed fullscreen and somehow it works

**Comment by ardahan1423** [comment]
thank you for your message i will try

metzenbaum98 <notifications@github.com>, 21 Oca 2021 Per, 01:01 tarihinde
şunu yazdı:

**Comment by ardahan1423** [comment]
1366x768 is he working my friend

DeepX 1337 <ardahanreis990@gmail.com>, 21 Oca 2021 Per, 03:27 tarihinde
şunu yazdı:

**Comment by MrFums** [comment]
Will be added in the future (support for different resolutions). Please join the [discord server](https://discord.com/invite/QFC46XKzxU) so I can assist you and let you know when it is added.
