### ISSUE TITLE
valbot doesn't work properly 

### ISSUE THREAD

**Issue by NOTDeaThNote** [MrFums/Valbot#53]
hello ,idk what im doin wrong but everytime i use the bot it finds the play button but after it snaps into the plus sign to invite people then to the start button but it is already stuck in the invite screen :c
![unknofgfgwn](https://user-images.githubusercontent.com/51106560/103315341-9345c280-4a25-11eb-83cb-7156fd6e0061.png)

**Comment by MrFums** [comment]
What resolution are you?

**Comment by sogoeslight** [comment]
Bot just trying to find some friends((

**Comment by NOTDeaThNote** [comment]
1600x900 , i kinda fixed it by adding my own photos but still sometimes fails

**Comment by NOTDeaThNote** [comment]
ik my res is garbage but that's what i have for now ,im upgrading to 1080p 144h ,but i just need to reach the knife tear 50

**Comment by MrFums** [comment]
https://github.com/MrFums/Valbot#requirements

`Only works on 1920 x 1080 resolution. If you wish to add a custom resolution, you need to get your own version of the images from the images folder, call them EXACTLY the same name and replace the original files.`
