### ISSUE TITLE
Bot doesn't work for me

### ISSUE THREAD

**Issue by utkangencpsn** [MrFums/Valbot#56]
Hi!
Firstly, I opened PackageInstaller as Administrator.
Then, I opened main and entered 1 in the console.
But, it closed a few seconds ago and it doesn't worked.

**Comment by berkakdal** [comment]
aynı sorun bende de var

**Comment by MrFums** [comment]
Please join the [discord server ](https://discord.com/invite/QFC46XKzxU)so I can help you and possibly get you to screen share so I can see what is happening. Thanks
