### ISSUE TITLE
Ayy

### ISSUE THREAD

**Issue by zeyfx** [MrFums/Valbot#57]
I play using this resolution
1366x768 
everything is fine but when a start the bot its just searching play button
OS: windows 10 - 20H2

**Comment by iNfeKTzia** [comment]
"Only works on 1920 x 1080 resolution. If you wish to add a custom resolution, you need to get your own version of the images from the images folder, call them EXACTLY the same name and replace the original files."

**Comment by gratv** [comment]
But, how i get my own images? what is the folder

**Comment by MrFums** [comment]
The folder called images where Valbot is installed.
