### ISSUE TITLE
Won't restart if Valorant launchers to "PLAY" launcher instead of direct game.

### ISSUE THREAD

**Issue by yungdetour** [MrFums/Valbot#62]
I don't know what determines whether you get the big "PLAY" button launcher or the shortcut directly opens to the Valorant game, but when it restarts and I get the launcher, the bot will keep trying to open Valorant and will get stuck.

**Comment by MrFums** [comment]
I believe you have to save account password for login

**Comment by MrFums** [comment]
assuming fixed

**Comment by yungdetour** [comment]
sorry for not updating, not fixed. i tried saving account info, etc. but didn't work. just been working around it by manually clicking.

**Comment by MrFums** [comment]
Alright. Not sure why this is still happening and how to change it. IF you could get me a print screen of the launcher when it says play I will be hopefully able to fix it.

**Comment by tkien212** [comment]
@MrFums This also happened to me. I believe when the game got forced closed, sometimes it doesn't launch automatically. I'm using [Deceived](https://github.com/molenzwiebel/Deceive/) to appear offline and don't have to start my side macro to search for play/launch button anymore

**Comment by yungdetour** [comment]
> @MrFums This also happened to me. I believe when the game got forced closed, sometimes it doesn't launch/play automatically. I'm using [Deceived](https://github.com/molenzwiebel/Deceive/) to appear offline and don't have to start my side macro to search for play/launch button anymore

Sounds like a good solution, I'll try that out. Thanks!

**Comment by MrFums** [comment]
Assuming fixed.
