### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by disterisk** [MrFums/Valbot#63]
so after about 8 games my valbot always crashes
it happened twice now
please fix

**Comment by MrFums** [comment]
How long do these 8 games last? Its not based on the amount of games you have played but the time the program has been running.

**Comment by MrFums** [comment]
This is a limitation with your computer. Not to worry though; you can fix it with the [latest version ](https://github.com/MrFums/Valbot/releases/latest). Go to `bot.py` then go to line 31 or whatever line is `self.secondsuntilrestart = 3600`. Change the 3600 to a number lower than 40 minutes so go with 30 minutes. This needs to be converted to seconds so 30 minutes in seconds is 1800. Change the line to `self.secondsuntilrestart = 1800` and run the program.

Also please join the server so I can help you in the future. https://discord.com/invite/QFC46XKzxU
