### ISSUE TITLE
Does not detect play button is selected after new update Valorant 2.01?

### ISSUE THREAD

**Issue by daray21** [MrFums/Valbot#65]
After they made the changes to Split (the map), the bot doesn't recognize that the play button is selected. It will move the mouse over to the play button and click it, but it doesn't recognize that it clicked it already. I think the new update changed the colors of the background or changed the color when you hover over the play button or something .

**Comment by zZIRZO** [comment]
Hi, did you find a solution?

**Comment by tkien212** [comment]
Line 335 on bot.py
Try changing:
onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.8)
To:
onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.6)

**Comment by MrFums** [comment]
The fix @tkien212 suggested (probably) will work, I say that because I haven't tested it. I will fix the program very soon to work with the latest patch.

**Comment by MrFums** [comment]
Has been fixed and also a discord has been made. Please join so I can help you in the future and notify you of future updates https://discord.com/invite/QFC46XKzxU
