### ISSUE TITLE
Bot Crashes after 8 matches

### ISSUE THREAD

**Issue by Garryonyoutube** [MrFums/Valbot#67]
Happens every time I use the bot, bot shuts off at around 40 minutes and 8 matches

**Comment by MrFums** [comment]
This is a limition with your computer. Not to worry though; you can fix it with the [latest version ](https://github.com/MrFums/Valbot/releases/latest). Go to `bot.py` then go to line 31 or whatever line is `self.secondsuntilrestart = 3600`. Change the 3600 to a number lower than 40 minutes so go with 30 minutes. This needs to be converted to seconds so 30 minutes in seconds is 1800. Change the line to `self.secondsuntilrestart = 1800` and run the program.
