### ISSUE TITLE
When I run the bot, it only searches for and clicks the "play button" nothing else.

### ISSUE THREAD

**Issue by danglir** [MrFums/Valbot#68]
When I run the bot, it only searches for the "play button", detects it, and then loops.
I'm running fullscreen, I tried windows borderless.
My resolution is 1920x1080, and I'm also using the Valorant player card.
I also tried the previous version 1.7.7, but it still had the same problem.
Any solutions? Thanks!

**Comment by danglir** [comment]
Ah, I figured out the problem, ever since the new Valorant update, the background screen changed, meaning that the bot's images in the "image" folder are outdated and won't work. Later I will fix this by taking new screenshots on my end, but this should be a patch in newer releases.

**Comment by tkien212** [comment]
OP said he will fix in the new version
For now, this is my fix. You can do your own images too

Line 335 on bot.py
Try changing:
onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.8)
To:
onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.6)

**Comment by danglir** [comment]
> OP said he will fix in the new version
> For now, this is my fix. You can do your own images too
> 
> Line 335 on bot.py
> Try changing:
> onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.8)
> To:
> onplay2 = pyautogui.locateOnScreen("images/onplay.png", grayscale=True, confidence=0.6)

Thank you! I'll try it now.

**Comment by MrFums** [comment]
Fixed in latest release
