### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Veyral** [MrFums/Valbot#71]
As stated in the title, I didnt know what caused this cause mostly I let the bot do it own things
When i came back i was greeted with that error in bot, could you please check what seems to be the issue?

![image](https://user-images.githubusercontent.com/40767003/107443180-ece3f580-6b6a-11eb-9bf2-8696810ec6c4.png)

**Comment by MrFums** [comment]
Fixed in 2.2
