### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by pukiskun** [MrFums/Valbot#73]
im sorry but i have encounter an issue, the bot seems stuck at

 [√] DETECTED PLAY BUTTON

 [-] DETECTING IF PLAY BUTTON IS SELECTED

 [!] DETECTED THAT PLAY BUTTON IS NOT SELECTED

and kept looping on that step over and over

**Comment by YaBoiSev** [comment]
I've had this problem before. try going into the images folder and updating the images by taking a screenshot and cropping the specific screen places. for example, if the file's name is "start.png" (IDK if it's an actual file name) and the image is a start button, take a screenshot of the start button in your Valorant client and name it the same name and replace it in your images folder. the problem might repeat for some other buttons as well, but if you update the pictures this way it should work properly

**Comment by Kertpunk** [comment]
I've had this problem before. try going into the images folder and updating the images by taking a screenshot and cropping the specific screen places. for example, if the file's name is "start.png" (IDK if it's an actual file name) and the image is a start button, take a screenshot of the start button in your Valorant client and name it the same name and replace it in your images folder. the problem might repeat for some other buttons as well, but if you update the pictures this way it should work properly

**Comment by MrFums** [comment]
Newest version available on my discord server, link is at the top of the read me file
