### ISSUE TITLE
Bonjour,

### ISSUE THREAD

**Issue by tontoned07** [MrFums/Valbot#74]
Bonjour, à chaque fois que je lance le programme il cherche le bouton play mais ne trouve pas. voice une phot§o de mon écran. Merci
![Val](https://user-images.githubusercontent.com/56596900/117017588-00c76f80-acf4-11eb-9101-2a750e52b5d9.jpg)

**Comment by MrFums** [comment]
Your resolution must be 1920x1080 for the bot to function. You can change the image resolution in the `change_resolution.txt` text file,. All information you need is in there.
