### ISSUE TITLE
not finding play again button

### ISSUE THREAD

**Issue by guwopg0d** [MrFums/Valbot#9]
whenever it finishes a game, it waits for the screen where the 'play again' button can be seen, but in the console in never seems to find it for some reason? i have installed everything correctly and play in fullscreen windowed 1920x1080. any idea how to fix?

**Comment by MrFums** [comment]
Try fullscreen. Are you using v1.5.1?

**Comment by guwopg0d** [comment]
ill try fullscreen.
yes i downloaded the 1.5.1 zip, extracted it and added a valorant shortcut.
also sometimes when the game is finished it stays on that loading triangle so unless i manually click on the play button at the top, it gets stuck..
really like the randomizer tho!

**Comment by guwopg0d** [comment]
just tried 1920x1080 fullscreen, and it already gets stuck on the first step; finding play button-
i made sure i had all the dependencies and nothing else running..

**Comment by MrFums** [comment]
Try making your own version of the images in the `images/` folder. Make sure that they are the exact same name.

**Comment by Zuanvl** [comment]
same problem here

**Comment by Zuanvl** [comment]
maybe because they moved the play again button to the bottom of the screen?

**Comment by Zuanvl** [comment]
i edited the y axis play again statement on the bot and it worked fine

**Comment by guwopg0d** [comment]
how did you do that if i may ask? what value on which line did you edit?
and what resolution/screen mode do you use? ty :) 

if i make my own images, do they have to be the exact same size as well?
and is there a fix if it stays on the loading triangle?

sorry if i ask so many questions, but i really want it to work :p

**Comment by MrFums** [comment]
>  resolution/screen mode

1920 x 1080

> if i make my own images, do they have to be the exact same size as well

Yes, try to make them almost exactly the same

> and is there a fix if it stays on the loading triangle?

Loading triangle is client desync that happens for unknown reasons. XP is still counted but not added onto your account until after the sync, currently there is no fast way to get around this other than calling `playbutton `function after `result `function instead of calling `playagain`

**Comment by Zuanvl** [comment]
![Capture](https://user-images.githubusercontent.com/73916707/98243526-a8abec80-1fa0-11eb-842c-4cd8caa20068.PNG)
93 and 103

**Comment by Zuanvl** [comment]
You can temporarily replace it like mine while waiting for the dev to update the bot

**Comment by guwopg0d** [comment]
> Loading triangle is client desync that happens for unknown reasons. XP is still counted but not added onto your account until after the sync, currently there is no fast way to get around this other than calling `playbutton `function after `result `function instead of calling `playagain`

maybe a fix for the next update would be something like; if it looked for the play again button 5 times and still didnt find it (because of desync issue), then it would change to the normal play button at the top?
i'm not sure if that's possible but just to give you an idea ;p

> (picture)
> 93 and 103

thanks! ill give it a try later

**Comment by MrFums** [comment]
> maybe a fix for the next update would be something like; if it looked for the play again button 5 times and still didnt find it (because of desync issue), then it would change to the normal play button at the top?

Thank you for the suggestion. Will add it.

**Comment by MrFums** [comment]
Suggestion added in 1.7
